name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ 386, amd64, arm64, ppc64, ppc64le ]
        exclude:
          - os: darwin
            arch: 386
          - os: darwin
            arch: ppc64
          - os: windows
            arch: ppc64
          - os: darwin
            arch: ppc64le
          - os: windows
            arch: ppc64le
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18'
      - run: |
          echo "::set-output name=name::.exe"
        if: matrix.os == 'windows'
        id: ext
      - run: |
          make \
            EXTENSION_NAME=${{steps.ext.outputs.name}} \
            MAIN_VERSION=${GITHUB_REF:10} \
            build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - name: "Upload binaries"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/allurectl_${{ matrix.os }}_${{ matrix.arch }}${{steps.ext.outputs.name}}
          asset_name: allurectl_${{ matrix.os }}_${{ matrix.arch }}${{steps.ext.outputs.name}}
          asset_content_type: application/octet-stream
