name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, darwin ]
        arch: [ amd64, arm64]
        # exclude:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18'
      - run: |
          go build -o ./allurestat_${{ matrix.os }}_${{ matrix.arch }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      # - run: |
      #     gh auth login
      #     gh auth status
      - name: "Upload binaries"
        uses: actions/upload-release-asset@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./allurestat_${{ matrix.os }}_${{ matrix.arch }}
          asset_name: allurestat_${{ matrix.os }}_${{ matrix.arch }}
          asset_content_type: application/octet-stream
