name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ amd64, arm64,]
        # exclude:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18'
      - run: |
          echo "::set-output name=name::.exe"
        if: matrix.os == 'windows'
        id: ext
      - run: |
            go build -o allurectl_${{ matrix.os }}_${{ matrix.arch }}${{steps.ext.outputs.name}} 
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - name: "Upload binaries"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./allurestat_${{ matrix.os }}_${{ matrix.arch }}${{steps.ext.outputs.name}}
          asset_name: allurestat_${{ matrix.os }}_${{ matrix.arch }}${{steps.ext.outputs.name}}
          asset_content_type: application/octet-stream
